set(_CATKIN_CURRENT_PACKAGE "raven_control")
set(raven_control_VERSION "0.0.0")
set(raven_control_MAINTAINER "bgusigma <bgusigma@todo.todo>")
set(raven_control_PACKAGE_FORMAT "2")
set(raven_control_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(raven_control_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(raven_control_BUILDTOOL_DEPENDS "catkin")
set(raven_control_BUILDTOOL_EXPORT_DEPENDS )
set(raven_control_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(raven_control_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(raven_control_TEST_DEPENDS )
set(raven_control_DOC_DEPENDS )
set(raven_control_URL_WEBSITE "")
set(raven_control_URL_BUGTRACKER "")
set(raven_control_URL_REPOSITORY "")
set(raven_control_DEPRECATED "")